config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users
  resources :campaigns do
    resources :discussion_topics do
      resources :comments, only: [:create, :destroy]
    end
    resources :tags
    resources :todos
    resources :comments, only: [:create, :destroy]
  end
end

app/models/discussion_topic.rb
class DiscussionTopic < ApplicationRecord
  belongs_to :campaign
  has_many :comments, as: :commentable
  validates :title, presence: true
  validate :one_topic_per_user_per_campaign

  private

  def one_topic_per_user_per_campaign
    if DiscussionTopic.where(user_id: user_id, campaign_id: campaign_id).exists?
      errors.add(:base, "You can only create one discussion topic per campaign.")
    end
  end
end

app/controllers/discussion_topics_controller.rb
class DiscussionTopicsController < ApplicationController
  before_action :set_campaign
  before_action :set_discussion_topic, only: [:edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :novice_limit, only:[:new, :create]
  def show
    @discussion_topic = DiscussionTopic.find(params[:id])
    @commentable = @discussion_topic
  end
  def edit
  end
  def index
    @discussion_topics = @campaign.discussion_topics
  end
  def update
    if @discussion_topic.update(discussion_topic_params)
      redirect_to campaign_discussion_topic_path(@campaign, @discussion_topic), notice: 'Discussion topic Updated Successfully!.'
    else
      render :edit
    end
  end

  def new
    @discussion_topic = @campaign.discussion_topics.build
  end

  def create
    @discussion_topic = @campaign.discussion_topics.build(discussion_topic_params)
    @discussion_topic.user_id = current_user.id
    if @discussion_topic.save
      redirect_to campaign_discussion_topics_path(@campaign), notice: 'Discussion topic Created Successfully!.'
    else
      # redirect_to new_campaign_discussion_topic_path
      render :new, status: :unprocessable_entity
    end
  end
  def destroy
    @discussion_topic.destroy
    redirect_to campaign_discussion_topics_path(@campaign), notice: 'Discussion topic Destroyed Successfully!.'
  end
  private
  def set_campaign
    @campaign = Campaign.find_by(id: params[:campaign_id])
    unless @campaign
      flash[:alert] = 'Campaign not found'
      redirect_to campaigns_path
    end
  end
  def set_discussion_topic
    @discussion_topic = @campaign.discussion_topics.find(params[:id])
  end
  def authorize_user
    unless @discussion_topic.user_id == current_user.id
      redirect_to campaign_discussion_topic_path(@campaign, @discussion_topic), alert: 'You are not authorized to perform this action.'
    end
  end
  def discussion_topic_params
    params.require(:discussion_topic).permit(:title, :description)
  end
  def novice_limit
    return unless current_user.novice?
    if current_user.discussion_topics.where(campaign_id: @campaign.id).exists?
      redirect_to campaigns_path, notice: "You can only create one Discussion Topic per campaign."
    end

  end
end

app/helpers/discussion_topics_helper.rb
module DiscussionTopicsHelper
end

app/views/discussion_topics/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Edit Discussion Topic</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h1>Edit Discussion Topic</h1>
  
  <%= form_for [@campaign, @discussion_topic] do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <%= f.submit "Update", class: "btn btn-primary" %>
  <%= link_to "Cancel", campaign_discussion_topic_path(@campaign, @discussion_topic), class: "btn btn-default" %>
<% end %>

</div>

</body>
</html>

app/views/discussion_topics/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Test Project</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<h1>Discussion Topics</h1>
<div class="row">
  <% @discussion_topics.each do |discussion_topic| %>
    <div class="col-md-4">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title"><%= discussion_topic.title %></h5>
          <%= link_to 'Read more', campaign_discussion_topic_path(@campaign, discussion_topic), class: "btn btn-primary" %>
            <%= link_to 'Edit', edit_campaign_discussion_topic_path(@campaign, discussion_topic), class: "btn btn-warning" %>
            <%= link_to 'Delete', campaign_discussion_topic_path(@campaign, discussion_topic), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  <%= link_to 'Back', campaign_path(@campaign), class: 'btn btn-default'  %>

        </div>
      </div>
    </div>
  <% end %>

</div>
</body>
</html>

app/views/discussion_topics/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>New Discussion Topic</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
  <h2>Create New Discussion Topic</h2>
  <%= form_with(model: [@campaign, @discussion_topic], local: true) do |form| %>
    <% if @discussion_topic.errors.any? %>
      <div>
        <h4><%= pluralize(@discussion_topic.errors.count, "error") %> prohibited this discussion topic from being saved:</h4>
        <ul>
          <% @discussion_topic.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% elsif flash[:alert].present? %>
      <div class="alert alert-danger">
        <h4><%= flash[:alert] %></h4>
      </div>
    <% end %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
    
    <%= form.hidden_field :campaign_id, value: @campaign.id %>
    <%= form.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>
</body>
</html>

app/views/discussion_topics/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>New Discussion Topic</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
  <div class="container">
    <h1><%= @discussion_topic.title %></h1>

    <% if @discussion_topic.comments.any? %>
      <h3>Comments</h3>
      <ul>
        <% @discussion_topic.comments.each do |comment| %>
          <li>
            <strong><%= comment.user.username %>:</strong>
            <% if comment.respond_to?(:title) %>
              <%= comment.title %>
            <% else %>
              No content available for this comment.
            <% end %>
            <%= link_to 'Delete', campaign_discussion_topic_comment_path(@discussion_topic.campaign, @discussion_topic, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No comments yet.</p>
    <% end %>

<%= form_with(model: [@discussion_topic.campaign, @discussion_topic, Comment.new], url: campaign_discussion_topic_comments_path(@discussion_topic.campaign, @discussion_topic), method: :post) do |form| %>
      <% if form.object.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(form.object.errors.count, "error") %> prohibited this comment from being saved:</h2>
          <ul>
            <% form.object.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :title, "Your Comment" %>
        <%= form.text_area :title, class: "form-control" %>
      </div>

      <%= form.submit "Submit Comment", class: "btn btn-primary" %>
    <% end %>
  </div>
</body>
</html>