config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users
  resources :campaigns do
    resources :discussion_topics do
      resources :comments, only: [:create, :destroy]
    end
    resources :tags
    resources :todos
    resources :comments, only: [:create, :destroy]
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :parent, class_name: "Tag", optional: true
  has_many :sub_tags, class_name: "Tag", foreign_key: "parent_id", dependent: :destroy
  has_and_belongs_to_many :campaigns

  validates :name, presence: true

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_campaign, only: [:index, :new, :create, :edit, :update, :destroy]

  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.all
  end
  def new
    @tag = Tag.new
  end
  def show
  end
  def create
    @campaign = Campaign.find(params[:campaign_id])
    @tag = @campaign.tags.build(tag_params)
    if @tag.save
      redirect_to campaign_path(@campaign), notice: 'Tag Created Successfully!.'
    else
      render :new
    end
  end
  def edit
  end
  def update
    @tag = Tag.find(params[:id])
    @campaign = @tag.campaigns
    if @tag.update(tag_params)
      redirect_to campaign_tags_path(@campaign), notice: 'Tag Updated Successfully!'
    else
      render :edit
    end
  end
  def destroy
    @tag = Tag.find(params[:id])
    @campaign = @tag.campaigns
    @tag.destroy
    redirect_to campaign_tags_path(@campaign), notice: 'Tag Deleted Successfully!'
  end
  private
  def set_campaign
    @campaign = Campaign.find(params[:campaign_id])
  end
  def set_tag
    @tag = Tag.find(params[:id])
  end
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for [@campaign, @tag] do |form| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>
      <ul>
        <% @tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <% if @campaign %>
    <div class="form-group">
      <%= form.label :parent_id, "Parent Tag" %>
      <%= form.collection_select :parent_id, Tag.all, :id, :name, { prompt: true }, class: 'form-control' %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Edit Todo List</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
  <h1>Edit Tag </h1>

  <%= render 'form' %>

  <%= link_to 'Back', campaign_tags_path(@campaign), class: 'btn btn-secondary' %>
</div>
</body>
</html>

app/views/tags/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Test Project</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<body>
<div class="container">
  <h1>Tags</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to edit_campaign_tag_path(@campaign, tag), class: 'btn btn-primary' do %>
          <i class="glyphicon glyphicon-edit"></i> <!-- Edit Icon -->
        <% end %></td>
        <td><%= link_to campaign_tag_path(@campaign, tag), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
          <i class="glyphicon glyphicon-trash"></i> <!-- Delete Icon -->
        <% end %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Create Tag', new_campaign_tag_path(@campaign), class: 'btn btn-primary' %>
  <%= link_to 'Back', campaign_path(@campaign), class: 'btn btn-default'  %>

</div>
</body>
</html>

app/views/tags/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>New Tag</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
  <h1>New Tag</h1>

  <%= render 'form' %>

  <%= link_to 'Back', campaign_tags_path(@campaign), class: 'btn btn-secondary' %>
</div>
</body>
</html>