config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users
  resources :campaigns do
    resources :discussion_topics do
      resources :comments, only: [:create, :destroy]
    end
    resources :tags
    resources :todos
    resources :comments, only: [:create, :destroy]
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :campaign

  validates :title, :description, presence: true

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_campaign
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def index
    @todos = @campaign.todos
  end
  def new
    @todo = @campaign.todos.build
    authorize @todo, :new?

  end
  def create
    @todo = @campaign.todos.build(todo_params)

    if @todo.save
      redirect_to campaign_path(@campaign), notice: "Todo List Created Successfully!"
    else
      flash.now[:alert] = 'Failed to Create Todo List.'
      render :new
    end
  end
  def edit
  end
  def show
  end
  def update
    if @todo.update(todo_params)
      redirect_to campaign_todo_path(@campaign, @todo), notice: "Todo List Updated Successfully!"
    else
      flash.now[:alert] = 'Failed to update Todo List.'
      render :edit
    end
  end
  def destroy
    @todo.destroy
    redirect_to campaign_path(@campaign), notice: "Todo List deleted Successfully!"
  end
  private
  def todo_params
    params.require(:todo).permit(:title, :description)
  end
  def set_campaign
    @campaign = Campaign.find_by(id: params[:campaign_id])
    unless @campaign
      flash[:alert] = 'Campaign not found.'
      redirect_to campaigns_path
    end
  end
  def set_todo
    @todo = @campaign.todos.find(params[:id])
  end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= form_for [@campaign, @todo] do |form| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo list from being saved:</h2>
      <ul>
        <% @todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Edit Todo List</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
  <h1>Edit Todo List</h1>

  <%= render 'form' %>

  <%= link_to 'Back', campaign_todos_path, class: 'btn btn-secondary' %>
</div>
</body>
</html>

app/views/todos/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Test Project</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
  <h1>Todo Lists</h1>

  <% if @todos.any? %>
    <ul>
      <% @todos.each do |todo| %>
        <li><%= link_to todo.title %></li>
        <li><%= link_to todo.description %></li>
      <% end %>
    </ul>
  <% else %>
    <p>No todo lists found.</p>
  <% end %>

</div>
</body>
</html>

app/views/todos/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>New Todo List</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
  <h1>New Todo List</h1>

  <%= render 'form' %>

  <%= link_to 'Back', campaign_todos_path, class: 'btn btn-secondary' %>
</div>
</body>
</html>

app/views/todos/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Test Project</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
  <h1><%= @todo.title %></h1>
  <p><strong>Description:</strong> <%= @todo.description %></p>
  <%= link_to 'Edit', edit_campaign_todo_path(@campaign, @todo), class: 'btn btn-primary' %>
  <%= link_to 'Delete', campaign_todo_path(@campaign, @todo), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  <%= link_to 'Back', campaign_path(@campaign), class: 'btn btn-default'  %>
</div>
</body>
</html>