config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users
  resources :campaigns do
    resources :discussion_topics do
      resources :comments, only: [:create, :destroy]
    end
    resources :tags
    resources :todos
    resources :comments, only: [:create, :destroy]
  end
end

app/models/campaign.rb
# app/models/campaign.rb
class Campaign < ApplicationRecord

  belongs_to :user
  has_many :todos, dependent: :destroy
  has_many :discussion_topics, dependent: :destroy
  has_many :comments, as: :commentable
  has_and_belongs_to_many :tags
  has_many_attached :images

  validates :title, :purpose, :estimated_duration, presence: true
  validates :estimated_duration, inclusion: { in: ['within 1 week', 'within 1 month', 'within 3 months'] }

end

app/controllers/campaigns_controller.rb
# app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  # GET /campaigns
  def index
    @campaigns = Campaign.all
  end
  # GET /campaigns/1
  def show
    @campaign = Campaign.find(params[:id])
    @todo = @campaign.todos # Assuming you have a `todo` association in your `Campaign` model
  end
  # GET /campaigns/new
  # GET /campaigns/1/edit
  def edit
    @campaign = Campaign.find(params[:id])
    authorize @campaign
  end
  # POST /campaigns
  def new
    @campaign = Campaign.new
    authorize @campaign
  end
  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.user = current_user # Associate the current user with the campaign
    authorize @campaign # Authorize create action
    # binding.pry
    if @campaign.save
      redirect_to @campaign, notice: 'Campaign Created Successfully.'
    else
      flash.now[:alert] = 'Failed to create campaign: ' + @campaign.errors.full_messages.join(", ")
      render :new
    end
  end
  def update


    @campaign = Campaign.find(params[:id])

    authorize @campaign # Authorize update action
    binding.pry
    if @campaign.update(campaign_params)
      redirect_to @campaign, notice: 'Campaign Updated Successfully.'
    else
      flash.now[:alert] = 'Failed to update campaign: ' + @campaign.errors.full_messages.join(", ")

      render :edit
    end
  end
  # DELETE /campaigns/1
  def destroy
    @campaign = Campaign.find(params[:id])
    authorize @campaign # Authorize destroy action
    @campaign.destroy
    redirect_to campaigns_url, notice: 'Campaign Destroyed Successfully.'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end
    def authorize_user
      unless @campaign.user_id == current_user.id
        redirect_to campaigns_path(@campaign),alert: 'You are not authorized to perform this action.'
      end
    end

    # Only allow a list of trusted parameters through.
    def campaign_params
      params.require(:campaign).permit(:title, :purpose, :estimated_duration, images: []) # Permit images attribute
    end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Test Project</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    #preview-images {
      display: flex;
      flex-wrap: wrap;
    }
    .preview-image {
      max-width: 100px;
      max-height: 100px;
      margin: 5px;
    }
  </style>
</head>
<body>
  <%= form_with(model: @campaign, html: { id: 'campaign-form', multipart: true }) do |form| %>
    <% if campaign.errors.any? %>
      <div id="error">
        <h2><%= pluralize(campaign.errors.count, "error") %> Couldn't save this campaign</h2>
        <ul>
          <% campaign.errors.full_messages.each do |message| %>
            <li> <%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
    <div class="field">
      <%= form.label :purpose %>
      <%= form.text_area :purpose, class: 'form-control' %>
    </div>
    <div class="field">
      <%= form.label :estimated_duration %>
      <%= form.select :estimated_duration, ['within 1 week', 'within 1 month', 'within 3 months'], {}, class: 'form-control' %>
    </div>
    <div class="field">
      <%= form.label :images %>
      <%= form.file_field :images, id: 'image-input', multiple: true, class: 'form-control' %>
    </div>
    <div id="image-preview" class="field">
      <div id="preview-images">
        <% if campaign.images.attached? %>
          <% @campaign.images.each do |image| %>
      <%= image_tag image, style: "max-width: 100%; height: auto;" %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="actions">
      <%= form.submit 'Save', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <script>
    $(document).ready(function() {
      $('#image-input').change(function(e) {
        $('#preview-images').empty(); // Clear existing preview images
        var files = e.target.files;
        if (files && files[0]) {
          for (var i = 0; i < files.length; i++) {
            var reader = new FileReader();
            reader.onload = function(e) {
              $('#preview-images').append('<img src="' + e.target.result + '" class="preview-image">');
            };
            reader.readAsDataURL(files[i]);
          }
        }
      });
    });
  </script>
</body>
</html>

app/views/campaigns/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Test Project</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
  <h1>Edit Campaign</h1>
 
  <%= render 'form', campaign: @campaign %>
  <%= link_to 'Back', campaigns_path, class: 'btn btn-default' %>
</div>
</body>
</html>

app/views/campaigns/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Test Project</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Adjust image height and width */
    .campaign-image {
      max-width: 100%; /* Set maximum width to 100% */
      height: auto; /* Allow the image to adjust its height proportionally */
    }
    .card-text {
      word-wrap: break-word; /* Allow the purpose text to wrap onto multiple lines */
      whitespace: normal;
    }
  </style>
</head>
<body>
  <h1>Campaigns</h1>
<div class="container ">
  <%= link_to 'New Campaign', new_campaign_path, class: 'btn btn-primary' %>
  <div class="row">
  <% @campaigns.each do |campaign| %>
    <div class="col-md-6 col-lg-4"> <!-- Adjust the column widths here -->
    <div class="card mt-3" style="width:350px; height:450px;" >
        <% campaign.images.each do |image| %>
          <%= image_tag image, class: 'card-img-top' %>
        <% end %>
      <div class="card-body">
        <h4 class="card-title"><%= campaign.title %></h4>
        <p class="card-text"><strong>Purpose:</strong> <%= campaign.purpose %></p>
        <p class="card-text"><strong>Estimated Duration:</strong> <%= campaign.estimated_duration %></p>
        <%= link_to 'Show', campaign, class: 'btn btn-primary' %>
        <%= link_to 'Edit', edit_campaign_path(campaign), class: 'btn btn-secondary' %>
        <%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </div>
    </div>
    </div>
  <% end %>
</div>
</div>
</body>
</html>

app/views/campaigns/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Test Project</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
 <div class="container">
   <h1>New Campaign</h1>
    <% if policy(Campaign.new).create? %>
       <%= render 'form', campaign: @campaign %>
    <% else %>
      <p>You are not authorized to create a campaign.</p>
    <% end %>
    <%= link_to 'Back', campaigns_path, class: 'btn btn-default' %>
 </div>
<script>
  // Check if the flash message exists and its type is 'notice'
  <% if flash[:notice] %>
    // Display a success toast message
    toastr.success('<%= flash[:notice] %>');
  <% end %>
</script>


</body>
</html>

app/views/campaigns/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Test Project</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    <h1><%= @campaign.title %></h1>
   <% @campaign.images.each do |image| %>
      <%= image_tag image, style: "max-width: 100%; height: auto;" %>
    <% end %>

    <p><strong>Purpose:</strong> <%= @campaign.purpose %></p>
    <p><strong>Estimated Duration:</strong><%= @campaign.estimated_duration %></p>
    <p><strong>User:</strong><%= @campaign.user.username %></p>
        <p><strong>Status:</strong><%= @campaign.user.status %></p>

   <%= link_to 'Edit', edit_campaign_path(@campaign), class: 'btn btn-primary' %>
   <% if @campaign.todos.present? %>
   <%= link_to 'View Todo', campaign_todo_path(@campaign, @campaign.todos.first), class: 'btn btn-primary' %>
   <% else %>
  <p>No todo list found for this campaign.</p>
  <%= link_to 'Create Todo', new_campaign_todo_path(@campaign), class: 'btn btn-primary' %>
  <% end %>
  <%= link_to 'View Tags', campaign_tags_path(@campaign), class: 'btn btn-info' %>
  <%= link_to 'View Discussion Topics', campaign_discussion_topics_path(@campaign), class: 'btn btn-success' %>
<% if current_user.novice? && current_user.status == 'qualified' %>
  <% if current_user.discussion_topics.where(campaign_id: @campaign.id).exists? %>
    <p>Discussion topic already created for this campaign.</p>
  <% else %>
    <%= link_to 'Create Discussion Topic', new_campaign_discussion_topic_path(@campaign), class: 'btn btn-primary' %>
  <% end %>
<% end %>


  <h4>Comments</h4>
    <% if @campaign.comments.any? %>
    <div class="comments">
      <% @campaign.comments.each do |comment| %>
        <div class="comment">
          <p><strong><%= comment.user.username %>:</strong> <%= comment.title %></p>
        </div>
     <%= link_to 'Delete', campaign_comment_path(@campaign, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
     <% end %>
    </div>
  <% else %>
    <p>No comments yet.</p>
  <% end %>
  <%= form_with(model: [@campaign, Comment.new], url: campaign_comments_path(@campaign), method: :post) do |form| %>
    <div>
      <%= form.label :title, "Comment" %>
      <%= form.text_area :title, class: "form-control" %>
    </div>
    <br><%= form.submit "Add Comment", class: "btn btn-primary" %>
  <% end %>
  <!-- Button to view discussion topics -->
  <br><%= link_to 'Back', campaigns_path, class: 'btn btn-default' %>
</div>
</body>
</html>